import { Lato, Playfair_Display } from "next/font/google";
import "./globals.css";

// Import Playfair Display (Google Font)
const myDisplay = Playfair_Display({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--my-display",
});

// Import Lato (Google Font)
const myLato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--my-lato",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myDisplay.variable} ${myLato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
