# Generated by Django 5.1.7 on 2025-03-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanneed',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('needs', models.ManyToManyField(blank=True, related_name='needs', to='users.need')),
            ],
        ),
        migrations.AddField(
            model_name='humanneed',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='users.event'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='events',
            field=models.ManyToManyField(related_name='organisations', to='users.event'),
        ),
    ]
