# Generated by Django 5.1.7 on 2025-03-13 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_humanneed_day_need_status_event_humanneed_eventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
