# Generated by Django 5.1.7 on 2025-03-14 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_need_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField()),
                ('dateStart', models.DateField(default=django.utils.timezone.now)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('needs', models.ManyToManyField(blank=True, related_name='needs', to='users.need')),
            ],
        ),
    ]
