# Generated by Django 5.1.7 on 2025-03-13 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event_dateend_event_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
    ]
