# Generated by Django 5.1.7 on 2025-03-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_message_created_at_remove_thread_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
