# Generated by Django 5.1.7 on 2025-03-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event_description_event_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='needs',
        ),
        migrations.AddField(
            model_name='need',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.event'),
        ),
    ]
