# Generated by Django 5.1.7 on 2025-03-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_need_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='needs',
        ),
        migrations.AddField(
            model_name='event',
            name='needs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='users.need'),
        ),
    ]
