# Generated by Django 5.1.7 on 2025-03-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_event_needs_event_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='needs',
        ),
        migrations.AddField(
            model_name='event',
            name='needs',
            field=models.ManyToManyField(blank=True, null=True, related_name='needs', to='users.need'),
        ),
    ]
