# Generated by Django 5.1.7 on 2025-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_event_needs_event_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='status',
        ),
        migrations.AddField(
            model_name='financialneed',
            name='dateSubmit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialneed',
            name='dateSubmit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
