# Generated by Django 5.1.7 on 2025-03-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_need_status_financialneed_datesubmit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='needs',
            field=models.ManyToManyField(blank=True, related_name='needs', to='users.need'),
        ),
    ]
