# Generated by Django 5.1.7 on 2025-03-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_event_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialneed',
            name='foodCollected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='need',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='users.organisation'),
        ),
    ]
