# Generated by Django 5.1.7 on 2025-03-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_materialneed_foodcollected_alter_need_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanneed',
            old_name='day',
            new_name='dateSubmit',
        ),
    ]
